name: On push to main

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Conan
        uses: turtlebrowser/get-conan@main

      - name: Conan - Detect profile
        run: conan profile detect --force

      - name: Conan - Install requirements
        run: conan install . --output-folder=${{github.workspace}}/build --build=missing

      - name: CMake - Configuration
        run: cmake -B ${{github.workspace}}/build -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: CMake - Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Run tests
        run: ${{github.workspace}}/build/tests
